apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-storage-location
  namespace: openshift-adp
spec:
  configuration:
    velero:
      defaultPlugins:
        - kubevirt
        - aws
        - csi
        - openshift
      resourceTimeout: 10m
      featureFlags:
        - EnableCSI
    nodeAgent: 
      enable: true
      uploaderType: kopia
  backupLocations:
    - velero:
        provider: aws
        default: true
        credential:
          key: cloud
          name: cloud-credentials
        objectStorage:
          bucket: oadp-backups-293d43a1-16dd-456c-ae92-a693723c296f
          prefix: velero
        config:
          insecureSkipTLSVerify: "true"
          profile: default
          region: localstorage
          s3ForcePathStyle: "true"
          s3Url: https://s3.openshift-storage.svc:443
